version: '3'
services:
  app:
    container_name: docker-mongo-nucamp
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: mongo-nucamp
    image: mongo
    ports:
      - '27017:27017'